### ISSUE TITLE
Code Coverage

### ISSUE THREAD

**Issue by Rory-Finnegan** [dfdx/Boltzmann.jl#26]
It would nice to keep track of test coverage. Especially, given the number paths available with the newly refactored code. I'm a fan of [codecov](https://codecov.io), but [coveralls](https://coveralls.io) also works.

**Comment by dfdx** [comment]
I've never worked with codecov, but if I did everything right, coverage status should appear [here](https://codecov.io/github/dfdx/Boltzmann.jl) when all tests finished (which takes quite long on Travis).

**Comment by Rory-Finnegan** [comment]
Looks like coverage is slowing down the tests enough to cause travis to timeout.

**Comment by Rory-Finnegan** [comment]
I got this working. Coverage is available [here](https://codecov.io/github/Rory-Finnegan/Boltzmann.jl?branch=coverage)

**Comment by dfdx** [comment]
Nice work! Would you mind creating a PR for coverage? 

Also, I assume there's a nice picture with average coverage somewhere on codecov that we can put to README to have it on the "front page", but I can't see it on the site. Do you know if codecov supports it?

**Comment by Rory-Finnegan** [comment]
Yeah, it has a badge. I'll add it in before I open the PR.

**Comment by dfdx** [comment]
Since coverage is merged into master, I'm closing this issue.
