### ISSUE TITLE
Generic Test Harness & Benchmarking

### ISSUE THREAD

**Issue by Rory-Finnegan** [dfdx/Boltzmann.jl#28]
Given the flexible workflow for building custom RBMs it would be helpful to have a generic test harness & benchmarking function for people to test their custom RBMs with.

NOTE: I can work on this.

**Comment by dfdx** [comment]
Not sure how to make a generic harness for testing RBM, ConditionalRBM and, say, future OpenCL RBM, but if you have a vision, please go ahead. With the number of possible flows and configurations we have after refactoring, tests become super important, so any generalization is heavily welcome.

**Comment by dfdx** [comment]
Do we need something behind what we already have?

**Comment by dfdx** [comment]
Then let's consider currently exported functions as public and concentrate on them. We can add other functions later if needed.

**Comment by Rory-Finnegan** [comment]
Sounds good.

**Comment by Rory-Finnegan** [comment]
An initial attempt at providing generic testing & benchmarking functions for rbms can be found [here](https://github.com/Rory-Finnegan/Boltzmann.jl/blob/testing/src/test.jl)

**Comment by dfdx** [comment]
Nice! Do I understand correctly that `generate_dataset` incorporates some patterns into data so that RBM could actually learn something?

**Comment by Rory-Finnegan** [comment]
Yes. This way we can actually assess that the RBM can learn rather than just that the code runs.
