### ISSUE TITLE
Tests are too slow

### ISSUE THREAD

**Issue by dfdx** [dfdx/Boltzmann.jl#30]
Currently tests run more than 2 hours on Travis, which is unreasonably long. The main cause for this is a brute force approach in which we test every supported element type with every possible visible and hidden unit type for both - dense and sparse input - plus different sets of options. The principal question is how to exclude most flows, but keep coverage high. Any suggestions are welcome.

**Comment by Rory-Finnegan** [comment]
Reducing the sizes of the RBM and input data for those tests doesn't help enough?

**Comment by Rory-Finnegan** [comment]
Tests down to around 30-40 min with coverage and benchmarking [here](https://travis-ci.org/Rory-Finnegan/Boltzmann.jl/builds/114869240)

**Comment by dfdx** [comment]
I think we can also decompose tests into parts. Though we need to test every kind of visible and hidden units and every option, we don't need to test every _combination_ of units and options. Essentially, kinds of units affect only sampling functions, while options in most cases control some specific functions, independent of sampling and each other. There are other independencies that we can use to drastically reduce test time. 

(Ironically, exactly the same decomposition of independent parts is what distinguishes restricted Boltzmann machines from fully-connected Boltzmann machines :))
