### ISSUE TITLE
Convolutional RBM?

### ISSUE THREAD

**Issue by AStupidBear** [dfdx/Boltzmann.jl#37]

**Comment by dfdx** [comment]
There are currently no plans to introduce convolutional RBMs, but if anyone is willing to take initiative, I'll be more than glad to  provide all help I can.

**Comment by AStupidBear** [comment]
I have seen ```https://github.com/dfdx/cdbn```

**Comment by dfdx** [comment]
Code in that repository is not working properly and exists mostly for historical reasons. For close-to-julia code it makes sense to check out [original Matlab implementation][1]. As far as I can see, this code mostly fits into framework of Boltzmann.jl, so it should be pretty straightforward to port it here. Yet, accurate implementation still requires diving into the topic of convolutional networks and careful coding, which is pretty time-consuming. Thus I leave it to anyone interested with a promise to provide suggestions and tips. 



[1]: https://github.com/dustinstansbury/medal/blob/master/models/crbm.m
