### ISSUE TITLE
DBN redesign

### ISSUE THREAD

**Issue by dfdx** [dfdx/Boltzmann.jl#4]
Current DBN implementation simply uses a list of (anonymous) RBMs, but it seems like a more common approach for layered models is to give every layer a name (e.g. see SciKit Learn's [Pipeline][1] or design of [Mocha.jl][2]). It helps in debugging, allows working with named entities (instead of indexes) and enables interoperability with other tools. 

I have prepared [new implementation][3] that adds names to layers and allows to save DBN to Mocha-compatible HDF5 files (see [example][4] for details), but could miss some important use cases. I'm interested: 

 1. Is this implementation clear? Is it convenient? 
 2. Does it cover all important use cases? If not, what else should be done? 

Specifically, I'm curious to hear @jfsantos 's opinion.

[1]: http://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html
[2]: https://github.com/pluskid/Mocha.jl
[3]: https://github.com/dfdx/Boltzmann.jl/blob/dbn-redesign/src/dbn.jl
[4]: https://github.com/dfdx/Boltzmann.jl/blob/dbn-redesign/examples/mocha_export_example.jl

**Comment by pluskid** [comment]
Great! I just added an example of using stacked auto-encoder to do pre-training: http://mochajl.readthedocs.org/en/latest/tutorial/mnist-sDA.html . Might be good to add a similar tutorial example using DBN from Boltzmann.jl later.

**Comment by jfsantos** [comment]
I think it looks good, at least for the use cases I have in mind.
