### ISSUE TITLE
convert errors

### ISSUE THREAD

**Issue by shencebebetterme** [dfdx/Boltzmann.jl#41]
I'm using Julia v0.5 and encounter the following problem while calling "RBM" function

> MethodError: Cannot convert an object of type Tuple{Int64,Int64} to an object of type Array{Float64,1}
This may have arisen from a call to the constructor Array{Float64,1}(...),
since type constructors fall back to convert methods.
> in #RBM#2(::Float64, ::Type{T}, ::Type{T}, ::Type{T}, ::Type{T}, ::Int64, ::Int64) at /Users/cary/.julia/v0.5/Boltzmann/src/rbm.jl:69
 in Boltzmann.RBM{T,V,H}(::Type{T}, ::Type{T}, ::Type{T}, ::Int64, ::Int64) at /Users/cary/.julia/v0.5/Boltzmann/src/rbm.jl:69

this can be solved by changing how the "map" function acts in "RBM" function 

```
function RBM(T::Type, V::Type, H::Type,
             n_vis::Int, n_hid::Int; sigma=0.01)
    RBM{T,V,H}(map(T, rand(Normal(0, sigma), [n_hid, n_vis]...)),
             zeros(n_vis), zeros(n_hid))
end
```

**Comment by dfdx** [comment]
How do you invoke it?

**Comment by shencebebetterme** [comment]
when I try the provided MNIST example the above error occurs, so I run line by line and find that error is due to RBM function

`function run_mnist()
    X, y = testdata()  # test data is smaller, no need to downsample
    X = X ./ (maximum(X) - minimum(X))
    m = RBM(Degenerate, Bernoulli, 28*28, 10)
    fit(m, X, n_epochs=10, randomize=true)
    #plot_weights(m.W[1:64, :], (28, 28))
    return m
end
`

maybe it's because I use Julia v0.5, after the changes it works fine now, thank you very much!

**Comment by shencebebetterme** [comment]
also, can you give some instruction on how to add L1 penalty to the RBM?
from your codes I guess the hierarchy is like 

`decay_kind = @get_or_return(ctx, :weight_decay_kind, nothing)`
`function grad_apply_weight_decay!(rbm::RBM, X::Mat, dtheta::Tuple, ctx::Dict)`
`function update_classic!(rbm::RBM, X::Mat, dtheta::Tuple, ctx::Dict)`
`function fit_batch!(rbm::RBM, X::Mat, ctx = Dict())`
`function fit{T}(rbm::RBM{T}, X::Mat, opts::Dict{Any,Any}=Dict{Any,Any}())`

so it seems that L1 penalty info. is provided in "opts" dictionary in "fit" function, but there is no such a choice in "fit" function, the following is copied from your comment:

Options that can be provided in the "opts" dictionary:
 * :n_epochs - number of full loops over data (default: 10)
 * :batch_size - size of mini-batches to use (default: 100)
 * :randomize - boolean, whether to shuffle batches or not (default: false)
 * :gradient - function to use for calculating parameter gradients
               (default: gradient_classic)
 * :update - function to use to update weights using calculated gradient
             (default: update_classic!)
 * :scorer - function to calculate how good the model is at the moment
             (default: pseudo_likelihood)
 * :reporter - type for reporting intermediate results using `report()`
               function (default: TextReporter)

then how can I add L1 penalty to the RBM?

**Comment by dfdx** [comment]
L1 and L2 penalties are often called weight decay in neural network and RBM parlance. You are looking for 2 parameters (yeah, I should document them somehow...): 

 * `:weight_decay_kind` - either `:l1` or `l2` depending on the penalty type
 * `:weight_decay_rate` - corresponding rate of decay / multiplier of penalty

As you correctly noticed, you should put these 2 into `opts` parameters, e.g.:

```
fit(rbm, X, Dict(:weight_decay_kind=:l1, :weight_decay_rate=0.5))
```
or simpler: 
```
fit(rbm, X; weight_decay_kind=:l1, weight_decay_rate=0.5)
```

**Comment by shencebebetterme** [comment]
This works fine and I can add L1 weight decay now, thank you!

**Comment by dfdx** [comment]
You are welcome. Can I close this issue?

**Comment by shencebebetterme** [comment]
Ok
