### ISSUE TITLE
Package Status?

### ISSUE THREAD

**Issue by rofinn** [dfdx/Boltzmann.jl#42]
Are folks actively using this pkg? I haven't been using RBMs much lately, but I'd be happy to add some fixes for 0.5 and 0.6 if there was still demand.

**Comment by dfdx** [comment]
I tried to adapt it to Julia 0.6 some time ago, but too many dependent packages were broken at the moment. If you have time to check it again, I'll be very thankful. 

In general, I believe we should keep existing packages up to date with the latest version of Julia to have a healthy ecosystem and attract more people (who in turn will create more packages). At the same time, not all packages require strict backward compatibility with outdated versions of the language, so we may simply drop support for Julia 0.4 and 0.5.

**Comment by yuehhua** [comment]
@dfdx I am very excited to see this package!
But.....as I installed it by Pkg.add, and it doesn't work properly.
Would you fix it recently?

I am recently using Julia 0.6.

**Comment by rofinn** [comment]
Might be helpful to post the error.

**Comment by dfdx** [comment]
You may want to check out master, right now it passes all  the tests and all examples from README pass on Julia 0.6.

**Comment by yuehhua** [comment]
@rofinn Thanks for remind me.

@dfdx Thank you! It's surely passed!
