### ISSUE TITLE
Persistent CD is wrong

### ISSUE THREAD

**Issue by fissoreg** [dfdx/Boltzmann.jl#47]
Hello,

the following implementation of `persistent_contdiv` doesn't look right to me, am I missing something?

https://github.com/dfdx/Boltzmann.jl/blob/0625ed0df2ca254c18c40ef7c34ff7ae136ae1e6/src/rbm.jl#L214-L232

The problem is that `persistent_chain` is local to the function and the `:persistent_chain` field in `ctx` is never updated. I'll make a PR to propose the correct implementation.

PS: thanks for the great package! ;)

**Comment by dfdx** [comment]
Thanks again!
