### ISSUE TITLE
Cannot `convert` an object of type Tuple{Int64,Int64} to an object of type Array{Float64,1} 

### ISSUE THREAD

**Issue by hapify** [dfdx/Boltzmann.jl#49]
When I try to run the example given in README, there is a error shows:
![screen shot 2018-04-05 at 12 16 41 am](https://user-images.githubusercontent.com/26411352/38337684-a798ace4-3866-11e8-9012-f87658add75c.png)
I am using JuliaPro, (julia version 0.6.2.2).

**Comment by dfdx** [comment]
Please, checkout latest master, e.g. from Julia console: 

```
Pkg.checkout("Boltzmann")
```
I've created a new release / [PR to METADATA](https://github.com/JuliaLang/METADATA.jl/pull/14141), once it's merged, the same changes should be available with a regular update (`Pkg.update()`). 

Please re-open if it doesn't fix your issue.
