### ISSUE TITLE
LinearAlgebra dependency

### ISSUE THREAD

**Issue by cossio** [dfdx/Boltzmann.jl#53]
Just installed `Boltzmann` today. I get the following warning:

```
┌ Warning: Package Boltzmann does not have LinearAlgebra in its dependencies:
│ - If you have Boltzmann checked out for development and have
│   added LinearAlgebra as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with Boltzmann
```

**Comment by dfdx** [comment]
Yeah, when I was updating Boltzmann to Julia 1.0, Pkg didn't require listing built-in packages in dependencies, but now it does. #54 should fix it, I'll merge it and tag new version once all tests pass.

**Comment by cossio** [comment]
Great, thanks @dfdx
